### ISSUE TITLE
im stuck

### ISSUE THREAD

**Issue by mrharryhd** [XeroxDev/help.xeroxdev.de#4]
![image](https://github.com/XeroxDev/help.xeroxdev.de/assets/148923299/b775c7a8-23ef-40ff-9e20-549ed20dceda)

**Comment by XeroxDev** [comment]
Hello!

1. That's an issue with the application itself, so you've to contact the YTMDesktop team.
2. This isn't the correct channel for such support request which is why I'll /close this ticket again, please refer to the correct repository or the discord server.
